smtDiaryMember:
  caption:
    ja_JP: "メンバーの日記(最新4件表示)"
    en_US: "Show latest 4 diary entries of a specified member"
  description:
    ja_JP: "メンバーの日記エントリのうち､最新の4件を表示します｡"
    en_US: "Show latest 4 diary entries of a specified member"
  component: [diary, smtDiaryMember]
